version: "3"

services:
  apache:
    build:
      context: ./dockerfiles/apache
      args:
        - DB_HOST=${DB_HOST}
        - DB_NAME=${DB_NAME}
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    image: ashrhmn/wtl-php-apache
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./dockerfiles/apache/apache2.conf:/etc/apache2/apache2.conf
      - ./:/var/www/html/app
      - fs:/var/www/html/assets
    container_name: wtl-apache
    depends_on:
      - mysql
  files:
    image: filebrowser/filebrowser
    container_name: wtl-files
    ports:
      - ${FILE_BROWSER_PORT}:80
    volumes:
      - fs:/srv
  mysql:
    container_name: wtl-mysql
    build: ./dockerfiles/mysql
    image: ashrhmn/wtl-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootash
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    # ports:
    #   - 3307:3306
    volumes:
      #- ./dockerfiles/mysql_data:/var/lib/mysql
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    container_name: wtl-myadmin
    depends_on:
      - db
    image: phpmyadmin
    links:
      - mysql:db
    ports:
      - ${PHPMYADMIN_PORT}:80
volumes:
  fs:
    name: wtl-fs
  mysql_data:
    name: wtl-mysql-data
